config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
 
  get "users/add_new_users" => "users#add_new_users", as: :add_new_users
  post "users/create_new_users" => "users#create_new_users", as: :create_new_users
  resources :users

  resources :posts do
    resources :comments
  end

  resources :schedules
  resources :events
  resources :availabilities

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :user
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.joins(:user).where('users.establishment = ?', current_user.establishment).order(:week)
    @title = 'Schedules'
  end

  def show
    @schedule = Schedule.find(params[:id])
    @date = Date.commercial(@schedule.year, @schedule.week) #.strftime("%Y-%m-%d")
    @events = Event.joins(:user).where('users.establishment = ?', current_user.establishment)
    @title = 'Week ' + @schedule.week.to_s
  end

  def new
    @schedule = Schedule.new
    @availabilities = Availability.joins(:user).where('users.establishment = ?', current_user.establishment)
    @title = 'New schedule'
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.user = current_user
    if current_user.admin? && @schedule.save
        flash[:notice] = "Your schedule was created successfully."
        redirect_to @schedule
      else
        flash[:alert] = "There was a problem saving your schedule."
        redirect_to new_schedule_path
      end
  end

  def edit
    @schedule = Schedule.find(params[:id])
    @availabilities = Availability.joins(:user).where('users.establishment = ?', current_user.establishment)
    @title = 'Edit: Week ' + @schedule.week.to_s
  end

  def update
    schedule = Schedule.find(params[:id])
    if schedule.update_attributes schedule_params
      flash[:notice] = "Your schedule was updated successfully."
      redirect_to schedule
    else
      flash[:alert] = "There was a problem updating your schedule."
      redirect_to(:back)
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
      if @schedule.destroy
        flash[:notice] = "The schedule was deleted successfully."
        redirect_to schedules_path
      else
        flash[:alert] = "There was a problem deleting the schedule."
        redirect_to @schedule
      end
  end

  private
  def schedule_params
    params.require(:schedule).permit(
      :week, :year, :day_one, :day_two, :day_three, :day_four, :day_five, :day_six, 
      :day_seven, :d_one_nine, :d_one_ten, :d_one_eleven, :d_one_twelve, :d_one_thirteen, 
      :d_one_fourteen, :d_one_fifteen, :d_one_sixteen, :d_one_seventeen, :d_one_eighteen, 
      :d_one_nineteen, :d_one_twenty, :d_two_nine, :d_two_ten, :d_two_eleven, :d_two_twelve, 
      :d_two_thirteen, :d_two_fourteen, :d_two_fifteen, :d_two_sixteen, :d_two_seventeen, 
      :d_two_eighteen, :d_two_nineteen, :d_two_twenty, :d_three_nine, :d_three_ten,
      :d_three_eleven, :d_three_twelve, :d_three_thirteen, :d_three_fourteen, :d_three_fifteen, 
      :d_three_sixteen, :d_three_seventeen, :d_three_eighteen, :d_three_nineteen, :d_three_twenty, 
      :d_four_nine, :d_four_ten, :d_four_eleven, :d_four_twelve, :d_four_thirteen, :d_four_fourteen, 
      :d_four_fifteen, :d_four_sixteen, :d_four_seventeen, :d_four_eighteen, :d_four_nineteen, 
      :d_four_twenty, :d_five_nine, :d_five_ten, :d_five_eleven, :d_five_twelve, :d_five_thirteen, 
      :d_five_fourteen, :d_five_fifteen, :d_five_sixteen, :d_five_seventeen, :d_five_eighteen, 
      :d_five_nineteen, :d_five_twenty, :d_six_nine, :d_six_ten, :d_six_eleven, :d_six_twelve, 
      :d_six_thirteen, :d_six_fourteen, :d_six_fifteen, :d_six_sixteen, :d_six_seventeen, 
      :d_six_eighteen, :d_six_nineteen, :d_six_twenty, :d_seven_nine, :d_seven_ten, :d_seven_eleven, 
      :d_seven_twelve, :d_seven_thirteen, :d_seven_fourteen, :d_seven_fifteen, :d_seven_sixteen, 
      :d_seven_seventeen, :d_seven_eighteen, :d_seven_nineteen, :d_seven_twenty, :user_id
      )
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/create.html.erb
<h1>Schedules#create</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/destroy.html.erb
<h1>Schedules#destroy</h1>
<p>Find me in app/views/schedules/destroy.html.erb</p>

app/views/schedules/edit.html.erb
<h1 class="alt-title"> Edit Schedule </h1>

<%= week_calendar events: @availabilities do |date, availabilities| %>
  <%= date.day %>

  <% availabilities.each do |availability| %>
    <div>
    <% if availability.day && availability.night %>
      <%= availability.user.fname %> (Day) <br>
      <%= availability.user.fname %> (Night)
    <% elsif availability.day %> 
      <%= availability.user.fname %> (Day)
    <% else %>
      <%= availability.user.fname %> (Night)
    <% end %>
    </div>
  <% end %>

<% end %>

<%= simple_form_for @schedule, method: :put, :class=> '.form-inline' do |f| %>
<%= f.input :year %>
<%= f.input :week %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= f.input :day_one, label: 'Monday' %></th>
        <th> <%= f.input :day_two, label: 'Tuesday' %></th>
        <th> <%= f.input :day_three, label: 'Wednesday' %></th>
        <th> <%= f.input :day_four, label: 'Thursday' %></th>
        <th> <%= f.input :day_five, label: 'Friday' %></th>
        <th> <%= f.input :day_six, label: 'Saturday' %></th>
        <th> <%= f.input :day_seven, label: 'Sunday' %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.input :d_one_nine, placeholder: '9', label: false %></td>
        <td><%= f.input :d_two_nine, placeholder: '9', label: false %></td>
        <td><%= f.input :d_three_nine, placeholder: '9', label: false %></td>
        <td><%= f.input :d_four_nine, placeholder: '9', label: false %></td>
        <td><%= f.input :d_five_nine, placeholder: '9', label: false %></td>
        <td><%= f.input :d_six_nine, placeholder: '9', label: false %></td>
        <td><%= f.input :d_seven_nine, placeholder: '9', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_ten, placeholder: '10', label: false %></td>
        <td><%= f.input :d_two_ten, placeholder: '10', label: false %></td>
        <td><%= f.input :d_three_ten, placeholder: '10', label: false %></td>
        <td><%= f.input :d_four_ten, placeholder: '10', label: false %></td>
        <td><%= f.input :d_five_ten, placeholder: '10', label: false %></td>
        <td><%= f.input :d_six_ten, placeholder: '10', label: false %></td>
        <td><%= f.input :d_seven_ten, placeholder: '10', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_eleven, placeholder: '11', label: false %></td>
        <td><%= f.input :d_two_eleven, placeholder: '11', label: false %></td>
        <td><%= f.input :d_three_eleven, placeholder: '11', label: false %></td>
        <td><%= f.input :d_four_eleven, placeholder: '11', label: false %></td>
        <td><%= f.input :d_five_eleven, placeholder: '11', label: false %></td>
        <td><%= f.input :d_six_eleven, placeholder: '11', label: false %></td>
        <td><%= f.input :d_seven_eleven, placeholder: '11', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_twelve, placeholder: '12', label: false %></td>
        <td><%= f.input :d_two_twelve, placeholder: '12', label: false %></td>
        <td><%= f.input :d_three_twelve, placeholder: '12', label: false %></td>
        <td><%= f.input :d_four_twelve, placeholder: '12', label: false %></td>
        <td><%= f.input :d_five_twelve, placeholder: '12', label: false %></td>
        <td><%= f.input :d_six_twelve, placeholder: '12', label: false %></td>
        <td><%= f.input :d_seven_twelve, placeholder: '12', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_thirteen, placeholder: '13', label: false %></td>
        <td><%= f.input :d_two_thirteen, placeholder: '13', label: false %></td>
        <td><%= f.input :d_three_thirteen, placeholder: '13', label: false %></td>
        <td><%= f.input :d_four_thirteen, placeholder: '13', label: false %></td>
        <td><%= f.input :d_five_thirteen, placeholder: '13', label: false %></td>
        <td><%= f.input :d_six_thirteen, placeholder: '13', label: false %></td>
        <td><%= f.input :d_seven_thirteen, placeholder: '13', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_fourteen, placeholder: '14', label: false %></td>
        <td><%= f.input :d_two_fourteen, placeholder: '14', label: false %></td>
        <td><%= f.input :d_three_fourteen, placeholder: '14', label: false %></td>
        <td><%= f.input :d_four_fourteen, placeholder: '14', label: false %></td>
        <td><%= f.input :d_five_fourteen, placeholder: '14', label: false %></td>
        <td><%= f.input :d_six_fourteen, placeholder: '14', label: false %></td>
        <td><%= f.input :d_seven_fourteen, placeholder: '14', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_fifteen, placeholder: '15', label: false %></td>
        <td><%= f.input :d_two_fifteen, placeholder: '15', label: false %></td>
        <td><%= f.input :d_three_fifteen, placeholder: '15', label: false %></td>
        <td><%= f.input :d_four_fifteen, placeholder: '15', label: false %></td>
        <td><%= f.input :d_five_fifteen, placeholder: '15', label: false %></td>
        <td><%= f.input :d_six_fifteen, placeholder: '15', label: false %></td>
        <td><%= f.input :d_seven_fifteen, placeholder: '15', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_sixteen, placeholder: '16', label: false %></td>
        <td><%= f.input :d_two_sixteen, placeholder: '16', label: false %></td>
        <td><%= f.input :d_three_sixteen, placeholder: '16', label: false %></td>
        <td><%= f.input :d_four_sixteen, placeholder: '16', label: false %></td>
        <td><%= f.input :d_five_sixteen, placeholder: '16', label: false %></td>
        <td><%= f.input :d_six_sixteen, placeholder: '16', label: false %></td>
        <td><%= f.input :d_seven_sixteen, placeholder: '16', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_seventeen, placeholder: '17', label: false %></td>
        <td><%= f.input :d_two_seventeen, placeholder: '17', label: false %></td>
        <td><%= f.input :d_three_seventeen, placeholder: '17', label: false %></td>
        <td><%= f.input :d_four_seventeen, placeholder: '17', label: false %></td>
        <td><%= f.input :d_five_seventeen, placeholder: '17', label: false %></td>
        <td><%= f.input :d_six_seventeen, placeholder: '17', label: false %></td>
        <td><%= f.input :d_seven_seventeen, placeholder: '17', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_eighteen, placeholder: '18', label: false %></td>
        <td><%= f.input :d_two_eighteen, placeholder: '18', label: false %></td>
        <td><%= f.input :d_three_eighteen, placeholder: '18', label: false %></td>
        <td><%= f.input :d_four_eighteen, placeholder: '18', label: false %></td>
        <td><%= f.input :d_five_eighteen, placeholder: '18', label: false %></td>
        <td><%= f.input :d_six_eighteen, placeholder: '18', label: false %></td>
        <td><%= f.input :d_seven_eighteen, placeholder: '18', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_nineteen, placeholder: '19', label: false %></td>
        <td><%= f.input :d_two_nineteen, placeholder: '19', label: false %></td>
        <td><%= f.input :d_three_nineteen, placeholder: '19', label: false %></td>
        <td><%= f.input :d_four_nineteen, placeholder: '19', label: false %></td>
        <td><%= f.input :d_five_nineteen, placeholder: '19', label: false %></td>
        <td><%= f.input :d_six_nineteen, placeholder: '19', label: false %></td>
        <td><%= f.input :d_seven_nineteen, placeholder: '19', label: false %></td>
      </tr>
      <tr>
        <td><%= f.input :d_one_twenty, placeholder: '20', label: false %></td>
        <td><%= f.input :d_two_twenty, placeholder: '20', label: false %></td>
        <td><%= f.input :d_three_twenty, placeholder: '20', label: false %></td>
        <td><%= f.input :d_four_twenty, placeholder: '20', label: false %></td>
        <td><%= f.input :d_five_twenty, placeholder: '20', label: false %></td>
        <td><%= f.input :d_six_twenty, placeholder: '20', label: false %></td>
        <td><%= f.input :d_seven_twenty, placeholder: '20', label: false %></td>
      </tr>
    </tbody>
  </table>

  <%= f.button :submit %>

  <% end %>

app/views/schedules/index.html.erb
<body class="content-wrapper">
	<h1 class="post-title">All Schedules</h1>

	<div class="row">
		<div class="col-md-9 events-wrapper">
		<ul>
			<% @schedules.each do |schedule| %>
				<li> <%= link_to 'Week ' + schedule.week.to_s, schedule_path(schedule.id) %> </li>
			<% end %>
		</ul>
		</div>

		<div class="col-md-2">
			<% if current_user.admin? %>
			<%= link_to "Create a new schedule", new_schedule_path, class: "btn btn-default" %>
			<% else %>
			<% end %>
		</div>
	</div>
</body>

app/views/schedules/show.html.erb
<h1 class="alt-title"> Schedule: Week <%= @schedule.week %> </h1>
<div class="yield-container">
  <div class="row">
    <% if current_user.admin? %>
    <div class="col-md-10">
      <% else %>
      <% end %>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th> Monday <%= @schedule.day_one %></th>
            <th> Tuesday <%= @schedule.day_two %></th>
            <th> Wednesday <%= @schedule.day_three %></th>
            <th> Thursday <%= @schedule.day_four  %></th>
            <th> Friday <%= @schedule.day_five %></th>
            <th> Saturday <%= @schedule.day_six  %></th>
            <th> Sunday <%= @schedule.day_seven %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @schedule.d_one_nine? ? "9: #{@schedule.d_one_nine}" : "" %></td>
            <td><%= @schedule.d_two_nine? ? "9: #{@schedule.d_two_nine}" : "" %></td>
            <td><%= @schedule.d_three_nine? ? "9: #{@schedule.d_three_nine}" : "" %></td>
            <td><%= @schedule.d_four_nine? ? "9: #{@schedule.d_four_nine}" : "" %></td>
            <td><%= @schedule.d_five_nine? ? "9: #{@schedule.d_five_nine}" : "" %></td>
            <td><%= @schedule.d_six_nine? ? "9: #{@schedule.d_six_nine}" : "" %></td>
            <td><%= @schedule.d_seven_nine? ? "9: #{@schedule.d_seven_nine}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_ten? ? "10: #{@schedule.d_one_ten}" : "" %></td>
            <td><%= @schedule.d_two_ten? ? "10: #{@schedule.d_two_ten}" : "" %></td>
            <td><%= @schedule.d_three_ten? ? "10: #{@schedule.d_three_ten}" : "" %></td>
            <td><%= @schedule.d_four_ten? ? "10: #{@schedule.d_four_ten}" : "" %></td>
            <td><%= @schedule.d_five_ten? ? "10: #{@schedule.d_five_ten}" : "" %></td>
            <td><%= @schedule.d_six_ten? ? "10: #{@schedule.d_six_ten}" : "" %></td>
            <td><%= @schedule.d_seven_ten? ? "10: #{@schedule.d_seven_ten}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_eleven? ? "11: #{@schedule.d_one_eleven}" : "" %></td>
            <td><%= @schedule.d_two_eleven? ? "11: #{@schedule.d_two_eleven}" : "" %></td>
            <td><%= @schedule.d_three_eleven? ? "11: #{@schedule.d_three_eleven}" : "" %></td>
            <td><%= @schedule.d_four_eleven? ? "11: #{@schedule.d_four_eleven}" : "" %></td>
            <td><%= @schedule.d_five_eleven? ? "11: #{@schedule.d_five_eleven}" : "" %></td>
            <td><%= @schedule.d_six_eleven? ? "11: #{@schedule.d_six_eleven}" : "" %></td>
            <td><%= @schedule.d_seven_eleven? ? "11: #{@schedule.d_seven_eleven}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_twelve? ? "12: #{@schedule.d_one_twelve}" : "" %></td>
            <td><%= @schedule.d_two_twelve? ? "12: #{@schedule.d_two_twelve}" : "" %></td>
            <td><%= @schedule.d_three_twelve? ? "12: #{@schedule.d_three_twelve}" : "" %></td>
            <td><%= @schedule.d_four_twelve? ? "12: #{@schedule.d_four_twelve}" : "" %></td>
            <td><%= @schedule.d_five_twelve? ? "12: #{@schedule.d_five_twelve}" : "" %></td>
            <td><%= @schedule.d_six_twelve? ? "12: #{@schedule.d_six_twelve}" : "" %></td>
            <td><%= @schedule.d_seven_twelve? ? "12: #{@schedule.d_seven_twelve}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_thirteen? ? "13: #{@schedule.d_one_thirteen}" : "" %></td>
            <td><%= @schedule.d_two_thirteen? ? "13: #{@schedule.d_two_thirteen}" : "" %></td>
            <td><%= @schedule.d_three_thirteen? ? "13: #{@schedule.d_three_thirteen}" : "" %></td>
            <td><%= @schedule.d_four_thirteen? ? "13: #{@schedule.d_four_thirteen}" : "" %></td>
            <td><%= @schedule.d_five_thirteen? ? "13: #{@schedule.d_five_thirteen}" : "" %></td>
            <td><%= @schedule.d_six_thirteen? ? "13: #{@schedule.d_six_thirteen}" : "" %></td>
            <td><%= @schedule.d_seven_thirteen? ? "13: #{@schedule.d_seven_thirteen}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_fourteen? ? "14: #{@schedule.d_one_fourteen}" : "" %></td>
            <td><%= @schedule.d_two_fourteen? ? "14: #{@schedule.d_two_fourteen}" : "" %></td>
            <td><%= @schedule.d_three_fourteen? ? "14: #{@schedule.d_three_fourteen}" : "" %></td>
            <td><%= @schedule.d_four_fourteen? ? "14: #{@schedule.d_four_fourteen}" : "" %></td>
            <td><%= @schedule.d_five_fourteen? ? "14: #{@schedule.d_five_fourteen}" : "" %></td>
            <td><%= @schedule.d_six_fourteen? ? "14: #{@schedule.d_six_fourteen}" : "" %></td>
            <td><%= @schedule.d_seven_fourteen? ? "14: #{@schedule.d_seven_fourteen}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_fifteen? ? "15: #{@schedule.d_one_fifteen}" : "" %></td>
            <td><%= @schedule.d_two_fifteen? ? "15: #{@schedule.d_two_fifteen}" : "" %></td>
            <td><%= @schedule.d_three_fifteen? ? "15: #{@schedule.d_three_fifteen}" : "" %></td>
            <td><%= @schedule.d_four_fifteen? ? "15: #{@schedule.d_four_fifteen}" : "" %></td>
            <td><%= @schedule.d_five_fifteen? ? "15: #{@schedule.d_five_fifteen}" : "" %></td>
            <td><%= @schedule.d_six_fifteen? ? "15: #{@schedule.d_six_fifteen}" : "" %></td>
            <td><%= @schedule.d_seven_fifteen? ? "15: #{@schedule.d_seven_fifteen}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_sixteen? ? "16: #{@schedule.d_one_sixteen}" : "" %></td>
            <td><%= @schedule.d_two_sixteen? ? "16: #{@schedule.d_two_sixteen}" : "" %></td>
            <td><%= @schedule.d_three_sixteen? ? "16: #{@schedule.d_three_sixteen}" : "" %></td>
            <td><%= @schedule.d_four_sixteen? ? "16: #{@schedule.d_four_sixteen}" : "" %></td>
            <td><%= @schedule.d_five_sixteen? ? "16: #{@schedule.d_five_sixteen}" : "" %></td>
            <td><%= @schedule.d_six_sixteen? ? "16: #{@schedule.d_six_sixteen}" : "" %></td>
            <td><%= @schedule.d_seven_sixteen? ? "16: #{@schedule.d_seven_sixteen}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_seventeen? ? "17: #{@schedule.d_one_seventeen}" : "" %></td>
            <td><%= @schedule.d_two_seventeen? ? "17: #{@schedule.d_two_seventeen}" : "" %></td>
            <td><%= @schedule.d_three_seventeen? ? "17: #{@schedule.d_three_seventeen}" : "" %></td>
            <td><%= @schedule.d_four_seventeen? ? "17: #{@schedule.d_four_seventeen}" : "" %></td>
            <td><%= @schedule.d_five_seventeen? ? "17: #{@schedule.d_five_seventeen}" : "" %></td>
            <td><%= @schedule.d_six_seventeen? ? "17: #{@schedule.d_six_seventeen}" : "" %></td>
            <td><%= @schedule.d_seven_seventeen? ? "17: #{@schedule.d_seven_seventeen}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_eighteen? ? "18: #{@schedule.d_one_eighteen}" : "" %></td>
            <td><%= @schedule.d_two_eighteen? ? "18: #{@schedule.d_two_eighteen}" : "" %></td>
            <td><%= @schedule.d_three_eighteen? ? "18: #{@schedule.d_three_eighteen}" : "" %></td>
            <td><%= @schedule.d_four_eighteen? ? "18: #{@schedule.d_four_eighteen}" : "" %></td>
            <td><%= @schedule.d_five_eighteen? ? "18: #{@schedule.d_five_eighteen}" : "" %></td>
            <td><%= @schedule.d_six_eighteen? ? "18: #{@schedule.d_six_eighteen}" : "" %></td>
            <td><%= @schedule.d_seven_eighteen? ? "18: #{@schedule.d_seven_eighteen}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_nineteen? ? "19: #{@schedule.d_one_nineteen}" : "" %></td>
            <td><%= @schedule.d_two_nineteen? ? "19: #{@schedule.d_two_nineteen}" : "" %></td>
            <td><%= @schedule.d_three_nineteen? ? "19: #{@schedule.d_three_nineteen}" : "" %></td>
            <td><%= @schedule.d_four_nineteen? ? "19: #{@schedule.d_four_nineteen}" : "" %></td>
            <td><%= @schedule.d_five_nineteen? ? "19: #{@schedule.d_five_nineteen}" : "" %></td>
            <td><%= @schedule.d_six_nineteen? ? "19: #{@schedule.d_six_nineteen}" : "" %></td>
            <td><%= @schedule.d_seven_nineteen? ? "19: #{@schedule.d_seven_nineteen}" : "" %></td>
          </tr>
          <tr>
            <td><%= @schedule.d_one_twenty? ? "20: #{@schedule.d_one_twenty}" : "" %></td>
            <td><%= @schedule.d_two_twenty? ? "20: #{@schedule.d_two_twenty}" : "" %></td>
            <td><%= @schedule.d_three_twenty? ? "20: #{@schedule.d_three_twenty}" : "" %></td>
            <td><%= @schedule.d_four_twenty? ? "20: #{@schedule.d_four_twenty}" : "" %></td>
            <td><%= @schedule.d_five_twenty? ? "20: #{@schedule.d_five_twenty}" : "" %></td>
            <td><%= @schedule.d_six_twenty? ? "20: #{@schedule.d_six_twenty}" : "" %></td>
            <td><%= @schedule.d_seven_twenty? ? "20: #{@schedule.d_seven_twenty}" : "" %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-md-2">
      <% if current_user.admin? %>
      <%= link_to 'Edit schedule', edit_schedule_path, class: "btn btn-default" %><br><br>
      <%= link_to 'Delete schedule', schedule_path(@schedule), method: :delete, class: "btn btn-default" %><br><br>
      <% else %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= week_calendar events: @events, :start_date=> @date do |date, events| %>
      <%= date.day %>

      <% events.each do |event| %>
      <div>
        <%= link_to event.name, event_path(event.id) %>
      </div>
      <% end %>

      <% end %> 
    </div>
  </div> 
</div>

app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>