config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
 
  get "users/add_new_users" => "users#add_new_users", as: :add_new_users
  post "users/create_new_users" => "users#create_new_users", as: :create_new_users
  resources :users

  resources :posts do
    resources :comments
  end

  resources :schedules
  resources :events
  resources :availabilities

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :name, :start_time
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    events = Event.joins(:user).where('users.establishment = ?', current_user.establishment)
    
    @pending_events = []
    @past_events = []
    events.each do |event|
      if event.start_time >= Time.now
        @pending_events << event
      else
        @past_events << event
      end
    end
    @title = 'Events'
  end

  def show
    @event = Event.find(params[:id])
    @title = @event.name
  end

  def new
    @event = Event.new
    @title = 'New event'
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      flash[:notice] = "Your event was created successfully."
      redirect_to @event
    else
      flash[:alert] = "There was a problem saving your event."
      redirect_to new_event_path
    end
  end

  def edit
    @event = Event.find(params[:id])
    @title = 'Edit: ' + @event.name
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes event_params
      flash[:notice] = "Your event was updated successfully."
      redirect_to @event
    else
      flash[:alert] = "There was a problem updating your event."
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:notice] = "The event was deleted successfully."
      redirect_to events_path
    else
      flash[:alert] = "There was a problem deleting the event."
      redirect_to @event
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :start_time, :user_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1> Edit Event </h1>

<%= form_for @event, method: :put do |f| %> 
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name, autofocus: true %>
</div>

<div class="field">
	<%= f.label :start_time, 'When' %><br />
	<%= f.datetime_select :start_time %><br><br>
</div>

<div class="actions">
	<%= f.submit :Edit, class: 'btn btn-default' %>
</div>
<% end %>

app/views/events/index.html.erb
<body class="content-wrapper">
	<h1 class="post-title">All Events</h1>

	<div class="row">
	<div class="col-md-5 events-wrapper">
			<h3>Upcoming events:</h3>
			<% @pending_events.each do |event| %>
			<p>
				<%= link_to event.name, event_path(event.id) %>
			</p>
			<% end %>
		</div>

		<div class="col-md-5 events-wrapper">
			<h3>Past events:</h3>
			<% @past_events.each do |event| %>
			<p>
				<%= link_to event.name, event_path(event.id) %>
			</p>
			<% end %>
		</div>


		<div class="col-md-1">
			<% if current_user.admin? %>
			<%= link_to "Add a new event", new_event_path, class: "btn btn-default" %>
			<% else %>
			<% end %>
		</div>
	</div>
</body>

app/views/events/new.html.erb
<h1 class="alt-title"> New Event </h1>
Fill in the details for the event you would like to create.<br><br>

<%= simple_form_for @event do |f| %> 
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name, autofocus: true %>
</div>

<div class="field">
	<%= f.label :start_time, 'When' %><br />
	<%= f.datetime_select :start_time %><br><br>
</div>

<div class="actions">
	<%= f.submit "Create event!", class: 'btn btn-default' %>
</div>
<% end %>

app/views/events/show.html.erb
<h1> <%= @event.name %></h1>
Taking place on the: <%= @event.start_time.strftime("%d/%m/%Y at %H:%M") %>

<br><br>
<% if current_user.admin? %>
	<%= link_to 'Edit event', edit_event_path, class: "btn btn-default" %>
	<%= link_to 'Delete event', event_path(@event), method: :delete, class: "btn btn-default" %>
<% else %>
<% end %>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>