config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
 
  get "users/add_new_users" => "users#add_new_users", as: :add_new_users
  post "users/create_new_users" => "users#create_new_users", as: :create_new_users
  resources :users

  resources :posts do
    resources :comments
  end

  resources :schedules
  resources :events
  resources :availabilities

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	validates_presence_of :title, :body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.joins(:user).where('users.establishment = ?', current_user.establishment)
    @title = "Q&A"
  end

  def show
    @post = Post.find(params[:id])
    @title = @post.title
  end

  def new
    @post = Post.new
    @title = 'New question'
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if current_user != nil && @post.save
      flash[:notice] = "Your post was created successfully."
      redirect_to post_path @post
    else
      flash[:alert] = "There was a problem saving your post."
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    @title = 'Edit: ' + @post.title
  end

  def update
    post = Post.find(params[:id])
    if post.update_attributes post_params
      flash[:notice] = "Your question was updated successfully."
      redirect_to post_path post
    else
      flash[:alert] = "There was a problem updating your question."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "The question was deleted successfully."
      redirect_to posts_path
    else
      flash[:alert] = "There was a problem deleting the question."
      redirect_to post_path @post
    end
  end

  private
  def post_params
    params.require(:post).permit(:body, :title, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_for @post, method: :put do |f| %>
  <%= f.label :title, 'Question:' %> <br>
  <%= f.text_field :title, :maxlength => 75, :size => 60 %>
  <br><br>
  <%= f.label :body, 'Body:' %> <br>
  <%= f.text_area :body, :maxlength => 150, :class => "post-body" %>
  <br><br>
  <%= f.submit :Edit, class: 'btn btn-default' %>
<% end %>

app/views/posts/index.html.erb
<body class="content-wrapper">
<h1 class="post-title"> All questions </h1>

<div class="row">
	<div class="col-md-9">
		<ul>
			<% @posts.each do |post| %>
				<li class="list-group-item"> 
					<span class="badge"> <%= post.comments.length %></span>
					<%= link_to post.title, post_path(post) %>
				</li>
			<% end %>
		</ul>
	</div>

	<div class="col-md-3">
		<%= link_to "Ask a question", new_post_path, class: "btn btn-default" %>
	</div>

</div>
</body>

app/views/posts/new.html.erb
<h1 class="alt-title"> New Question </h1>

Fill in the details for the question you would like to ask. <br><br>
<%= form_for @post do |f| %>
  <%= f.label :title, 'Question:' %> <br>
 <%= f.text_field :title, :maxlength => 75, :size => 60%>

  <br><br>
  <%= f.label :body, 'Body:' %> <br>
  <%= f.text_area :body, :maxlength => 150, :class => "post-body" %>
  <br><br>
  IMPORTANT: you must be logged in to be able to post.
  <br><br>
  <%= f.submit :'Ask!', class: 'btn btn-default'  %>
<% end %>

app/views/posts/show.html.erb
<body class="content-wrapper">
	<div class="row">
		<div class="col-md-9">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><%= @post.title %></h3>
					<div class="time-stamp"><%= @post.created_at.strftime("%d/%m/%Y at %H:%M") %></div>
				</div>
				<div class="panel-body">
					<%= @post.body %>
					
				</div>
			</div>
			<div class="posted-by">
				Posted by: <%= @post.user.fname %>
			</div>


			<div class="panel panel-default">
				<ul class="list-group">
					<% @post.comments.each do |comment| %>
					<li class="list-group-item"> 
					<div class="time-stamp"><%= comment.created_at.strftime("%d/%m/%Y at %H:%M") %></div>
					<b><%= comment.user.fname %></b> 
						<%= comment.text %> <br>
						<% if current_user == @post.user || current_user.admin? %>
						<%= link_to 'Delete comment', post_comment_path(@post, comment), method: :delete %>
						<% else %>
						<% end %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>

		<div class="col-md-3">
			<% if current_user == @post.user || current_user.admin? %>
			<%= link_to 'Edit post', edit_post_path, class: "btn btn-default" %><br><br>
			<%= link_to 'Delete post', post_path(@post), method: :delete, class: "btn btn-default" %><br><br>
			<% else %>
			<% end %>
			<%= link_to 'Comment', new_post_comment_path(@post), class: "btn btn-default" %>
		</div>

	</div>
</body>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>