config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
 
  get "users/add_new_users" => "users#add_new_users", as: :add_new_users
  post "users/create_new_users" => "users#create_new_users", as: :create_new_users
  resources :users

  resources :posts do
    resources :comments
  end

  resources :schedules
  resources :events
  resources :availabilities

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
	belongs_to :user

	validates :date, uniqueness: true

	def start_time
        self.date.to_datetime ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  def index
    @availabilities = Availability.joins(:user).where('users.establishment = ?', current_user.establishment)
    @title = 'Availabilities'
  end

  def show
    @availability = Availability.find(params[:id])
    @title = @availability.user.fname + ": " + @availability.date.strftime("%d/%m/%Y")
  end

  def new
    @availability = Availability.new
    @availabilities = Availability.joins(:user).where('users.establishment = ?', current_user.establishment)
    #@availability = Array.new (7) {Availability.new}
    @events = Event.joins(:user).where('users.establishment = ?', current_user.establishment)
    @title = 'New availability'
  end

  def create
    @availability = Availability.new(availability_params)
    # @availability = params[:availability].values.collect { |availability| Availability.new(availability)}
    @availability.user = current_user
    if current_user != nil && @availability.save
      flash[:notice] = "Your availability has been saved successfully."
      redirect_to availabilities_path
    else
      flash[:alert] = "There was a problem saving your availability."
      redirect_to availabilities_path
    end
  end

  def edit
    @availability = Availability.find(params[:id])
    @availabilities = Availability.joins(:user).where('users.establishment = ?', current_user.establishment)
    @events = Event.joins(:user).where('users.establishment = ?', current_user.establishment)
    @title = 'Edit availability'
  end

  def update
    availability = Availability.find(params[:id])
    if availability.update_attributes availability_params
      flash[:notice] = "Your availability was updated successfully."
      redirect_to availabilities_path
    else
      flash[:alert] = "There was a problem updating your availability."
      redirect_to(:back)
    end
  end

  def destroy
    @availability = Availability.find(params[:id])
      if @availability.destroy
        flash[:notice] = "Your availability was deleted successfully."
        redirect_to availabilities_path
      else
        flash[:alert] = "There was a problem deleting your availability."
        redirect_to @availability
      end
  end

  private
  def availability_params
    params.require(:availability).permit(:user_id, :date, :day, :night)
  end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/create.html.erb
<h1>Availabilities#create</h1>
<p>Find me in app/views/availabilities/create.html.erb</p>

app/views/availabilities/destroy.html.erb
<h1>Availabilities#destroy</h1>
<p>Find me in app/views/availabilities/destroy.html.erb</p>

app/views/availabilities/edit.html.erb
<h1 class="alt-title"> Edit Availability </h1>

<%= week_calendar events: @availabilities do |date, availabilities| %>
  <%= date.day %>

  <% availabilities.each do |availability| %>
    <div>
    <% if availability.day && availability.night %>
      <%= availability.user.fname %> (Day) <br>
      <%= availability.user.fname %> (Night)
    <% elsif availability.day %> 
      <%= availability.user.fname %> (Day)
    <% else %>
      <%= availability.user.fname %> (Night)
    <% end %>
    </div>
  <% end %>

<% end %>

<%= month_calendar events: @events do |date, events| %>
<%= date.day %>

<% events.each do |event| %>
<div>
  <%= link_to event.name, event_path(event.id) %>
</div>
<% end %>

<% end %>

<%= simple_form_for @availability, method: :put do |f| %>
  <%= f.input :date %>
  <%= f.input :day %>
  <%= f.input :night  %>
  <%= f.button :submit %>
<% end %>

app/views/availabilities/index.html.erb
<h1 class="alt-title"> All Availabilities </h1>
<div class="row">
  <div class="col-md-11">
    <%= week_calendar events: @availabilities do |date, availabilities| %>
    <%= date.day %>

    <% availabilities.each do |availability| %>
    <div>
     <% if availability.day && availability.night %>
       <% if availability.user == current_user || current_user.admin? %>
       <%= link_to availability.user.fname + " (Day)", availability_path(availability) %><br>
       <%= link_to availability.user.fname + " (Night)", availability_path(availability) %>
       <% else %>
       <%= availability.user.fname %> (Day) <br>
       <%= availability.user.fname %> (Night)
       <% end %>
     <% elsif availability.day %> 
       <% if availability.user == current_user || current_user.admin? %>
       <%= link_to availability.user.fname + " (Day)", availability_path(availability) %>
       <% else %>
       <%= availability.user.fname %> (Day)
       <% end %>
     <% else %>
       <% if availability.user == current_user || current_user.admin? %>
       <%= link_to availability.user.fname + " (Night)", availability_path(availability) %>
       <% else %>
       <%= availability.user.fname %> (Night)
       <% end %>
     <% end %>
   </div>
   <% end %>

   <% end %>
 </div>

 <div class="col-md-1">
  <%= link_to "Add a new availability", new_availability_path, class: "btn btn-default" %>
</div>

</div>

app/views/availabilities/new.html.erb
<h1 class="alt-title"> New Availability </h1>

<%= week_calendar events: @availabilities do |date, availabilities| %>
  <%= date.day %>

  <% availabilities.each do |availability| %>
    <div>
    <% if availability.day && availability.night %>
      <%= availability.user.fname %> (Day) <br>
      <%= availability.user.fname %> (Night)
    <% elsif availability.day %> 
      <%= availability.user.fname %> (Day)
    <% else %>
      <%= availability.user.fname %> (Night)
    <% end %>
    </div>
  <% end %>

<% end %>

<%= month_calendar events: @events do |date, events| %>
<%= date.day %>

<% events.each do |event| %>
<div>
  <%= link_to event.name, event_path(event.id) %>
</div>
<% end %>

<% end %>

<%= simple_form_for @availability do |f| %>
  <%= f.input :date %>
  <%= f.input :day %>
  <%= f.input :night  %>
  <%= f.button :submit %>
<% end %>

<!-- The week availability form/table, will improve on this in the future

Date.today.wday
1.week.since(Date.today)
Date.today.cweek

<h3> Week <%= Date.today.cweek %> </h3>
<%= simple_form_for @availability, :class=> '.form-inline' do |f| %>
  <table class="table table-bordered table-condensed">
    <thead>
      <tr>
        <th colspan="2"> <%= f.input :date %></th>
        <th colspan="2"> <%= (Date.today + 1).strftime("%A %d") %></th>
        <th colspan="2"> <%= (Date.today + 2).strftime("%A %d") %></th>
        <th colspan="2"> <%= (Date.today + 3).strftime("%A %d") %></th>
        <th colspan="2"> <%= (Date.today + 4).strftime("%A %d") %></th>
        <th colspan="2"> <%= (Date.today + 5).strftime("%A %d") %></th>
        <th colspan="2"> <%= (Date.today + 6).strftime("%A %d") %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.input :day %></td>
        <td><%= f.input :night %></td>
        <td><%= f.input :day %></td>
        <td><%= f.input :night %></td>
        <td><%= f.input :day %></td>
        <td><%= f.input :night %></td>
        <td><%= f.input :day %></td>
        <td><%= f.input :night %></td>
        <td><%= f.input :day %></td>
        <td><%= f.input :night %></td>
        <td><%= f.input :day %></td>
        <td><%= f.input :night %></td>
        <td><%= f.input :day %></td>
        <td><%= f.input :night %></td>
        <td><%= f.button :submit %></td>
      </tr>
    </tbody>
  </table>
<%end %> -->

app/views/availabilities/show.html.erb
<h1> <%= @availability.date.strftime("%d/%m/%Y") %></h1>
Your availability: <br>
<ul>
	<% if @availability.day && @availability.night %>
		<li> Day </li>
		<li> Night </li>
	<% elsif @availability.day %> 
		<li> Day </li>
	<% else %>
		<li> Night </li>
	<% end %>
</ul>


<br><br>
<% if current_user.admin? || current_user == @availability.user %>
	<%= link_to 'Edit availability', edit_availability_path, class: "btn btn-default" %>
	<%= link_to 'Delete availability', availability_path(@availability), method: :delete, class: "btn btn-default" %>
<% else %>
<% end %>

app/views/availabilities/update.html.erb
<h1>Availabilities#update</h1>
<p>Find me in app/views/availabilities/update.html.erb</p>